version: '3.8'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin_standalone
    # Host mode solves 90% of DLNA/Discovery/Port issues
    network_mode: "host" 
    environment:
      - JELLYFIN_PublishedServerUrl=https://192.168.1.105:8096
      # Uncomment the next line only if the default driver fails
      # - LIBVA_DRIVER_NAME=i965
    volumes:
      - ${HOME_PATH}/jellyfin/config:/config
      - ${HOME_PATH}/jellyfin/cache:/cache
      - ${DATA_PATH}/media/shows:/data/tvshows
    devices:
      # We know from your ls -l that D128 is the Intel card
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card1:/dev/dri/card1
    restart: unless-stopped

  # Nginx Proxy Manager for managing reverse proxies and SSL
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - proxy_network
    ports:
      - '80:80'
      - '81:81' 
      - '443:443'
    volumes:
      - ${HOME_PATH}/npm/data:/data
      - ${HOME_PATH}/npm/letsencrypt:/etc/letsencrypt

networks:
  proxy_network:
    driver: bridge